### ISSUE TITLE
RuntimeError: dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by EinAeffchen** [spro/practical-pytorch#106]
```
Training for 2000 epochs...
Traceback (most recent call last):
  File ".\train.py", line 64, in <module>
    loss = train(*random_training_set(args.chunk_len))
  File ".\train.py", line 49, in train
    loss += criterion(output, target[c])
  File "C:\Users\leond\AppData\Local\Continuum\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\leond\AppData\Local\Continuum\Anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 759, in forward
    self.ignore_index, self.reduce)
  File "C:\Users\leond\AppData\Local\Continuum\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1442, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
  File "C:\Users\leond\AppData\Local\Continuum\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1328, in nll_loss
    if input.size(0) != target.size(0):
RuntimeError: dimension specified as 0 but tensor has no dimensions
```

Just tried to run train.py with the shakespeare.txt without changing anything

**Comment by joistick11** [comment]
This is because of pytorch version

**Comment by BlindElephants** [comment]
I'm also experiencing this. Any help or work around?

Thanks

**Comment by BlindElephants** [comment]
@joistick11 What is the proper version of PyTorch that should be run to avoid this problem?

**Comment by BlindElephants** [comment]
Nvm, corrected it in line based on answers found elsewhere on Github and Stack:

For example in the file: [ practical-pytorch/char-rnn-generation/train.py](https://github.com/spro/practical-pytorch/blob/master/char-rnn-generation/train.py), line 49:

```python
loss += criterion(output, target[c])
```

should be changed to:

```python
loss += criterion(output, target[c].unsqueeze(0))
```
