### ISSUE TITLE
Error while code execution in default setting

### ISSUE THREAD

**Issue by Saptakatha** [spro/practical-pytorch#12]
I am getting the following error while executing the code in default setting.

`Traceback (most recent call last):
  File "/home/sapto/Desktop/Translation/seq2seq_translation_tutorial.py", line 812, in <module>
    trainEpochs(encoder1, attn_decoder1, 75000, print_every=5000)
  File "/home/sapto/Desktop/Translation/seq2seq_translation_tutorial.py", line 678, in trainEpochs
    decoder, encoder_optimizer, decoder_optimizer, criterion)
  File "/home/sapto/Desktop/Translation/seq2seq_translation_tutorial.py", line 584, in train
    input_variable[ei], encoder_hidden)
  File "/home/sapto/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sapto/Desktop/Translation/seq2seq_translation_tutorial.py", line 355, in forward
    output, hidden = self.lstm(output, hidden)
  File "/home/sapto/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sapto/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/sapto/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 327, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/sapto/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 202, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/home/sapto/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 224, in forward
    result = self.forward_extended(*nested_tensors)
  File "/home/sapto/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 269, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/home/sapto/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 195, in forward
    hx, cx = hx
ValueError: not enough values to unpack (expected 2, got 1)

Process finished with exit code 1`

**Comment by spro** [comment]
I haven't seen this error before - are you using an up-to-date version of PyTorch?

**Comment by Saptakatha** [comment]
yep.. I am using the latest version of PyTorch..

Regards,
*Saptakatha Adak*
Visualization and Perception Lab
Department of Computer Science and Engineering
Indian Institute of Technology Madras
இந்தியா தொழில்நுட்ப கழகம் சென்னை
Chennai - 600036
Tamil Nadu
India

**Comment by spro** [comment]
Looking closer it seems you switched the GRU to a LSTM, which has slightly different inputs and outputs. The LSTM hidden states are stored as a tuple of tensors `(hx, cx)` whereas the GRU hidden state is a single tensor.

**Comment by Saptakatha** [comment]
Ok.. Thank you..
