### ISSUE TITLE
Batch support in seq2seq tutorial

### ISSUE THREAD

**Issue by spro** [spro/practical-pytorch#27]

**Comment by ehsanasgari** [comment]
Would you please add batching to the tutorial as well?

**Comment by vijendra-rana** [comment]
Hello, @spro  I have been working through extending with batch. My code is here https://github.com/vijendra-rana/Random/blob/master/translation_with_batch.py . I have created some fake data for this. But the problem is I am getting error in loss saying <pre>
RuntimeError: Trying to backward through the graph second time, but the buffers have already been freed. Please specify retain_variables=True when calling backward for the first time. 
</pre>
I understand we cannot have loss being backwarded twice but I don't see anywhere that I am doing it twice. 
Also I have question about masking how would you mask the loss at the encoder. Not sure how to implement it the encoder o/p being size (seq_len,batch,hidden_size) and mask being (batch_size,seq_len)

Thanks in advance for help :)

**Comment by spro** [comment]
I put a first version of the batched model at https://github.com/spro/practical-pytorch/blob/master/seq2seq-translation/seq2seq-translation-batched.ipynb via 31fdb61387e62948f6a24dc9a2dadd6d3221a73c

The biggest changes are using `pack_padded_sequence` before the encoder RNN and `pad_packed_sequence` after it, and the [masked cross entropy loss from @jihunchoi](https://github.com/pytorch/pytorch/issues/563#issuecomment-287982893) after decoding. For the decoder itself changes are minor because it only runs one time step at a time.

**Comment by vijendra-rana** [comment]
Thanks, @spro for your effort in putting these together. Your tutorials are really nice.

**Comment by ParpulovDmitry** [comment]
Hello, @spro ! Thanks for your tutorials!
Now i'm trying to parallel batched version of seq2seq on multiple GPU, and i'm stucked at encoder paralleling. I want to use nn.DataParallel for this purpose. 
DataParallel splits across batch dimensions, so i put input_lengths calculations inside forward function in encoder (like below) and modify some functions:

```
def random_batch(batch_size):
    input_seqs = []
    target_seqs = []
    # Choose random pairs
    for i in range(batch_size):
        pair = random.choice(pairs)
        input_seqs.append(indexes_from_sentence(input_lang, pair[0]))
        target_seqs.append(indexes_from_sentence(output_lang, pair[1]))
    return (input_seqs, target_seqs)

def create_padded_batches(batch):
    input_seqs, target_seqs = batch
    seq_pairs = sorted(zip(input_seqs, target_seqs), key=lambda p: len(p[0]), reverse=True)
    input_seqs, target_seqs = zip(*seq_pairs)
    input_lengths = [len(s) for s in input_seqs]
    input_padded = [pad_seq(s, max(input_lengths)) for s in input_seqs]
    target_lengths = [len(s) for s in target_seqs]
    target_padded = [pad_seq(s, max(target_lengths)) for s in target_seqs]
    
    input_var = Variable(torch.LongTensor(input_padded))#.transpose(0, 1)
    target_var = Variable(torch.LongTensor(target_padded))#.transpose(0, 1)
    
    if USE_CUDA:
        input_var = input_var.cuda()
        target_var = target_var.cuda()
    
    return input_var, input_lengths, target_var, target_lengths

class EncoderRNN(nn.Module):
    ## .... init ....
    def forward(self, batch, hidden=None):
        input_seqs, input_lengths, target_seqs, target_lengths = create_padded_batches(batch)

        embedded = self.embedding(input_seqs)
        packed = pack_padded_sequence(embedded, input_lengths, batch_first=True)  # because parallel splits across batch

        outputs, hidden = self.gru(packed, hidden)
        outputs, output_lengths = pad_packed_sequence(outputs) # unpack (back to padded)
        outputs = outputs[:, :, :self.hidden_size] + outputs[:, : ,self.hidden_size:] # Sum bidirectional outputs        
        outputs = outputs.transpose(0,1)
        return outputs, hidden
```

At one GPU all is ok (i set device_ids=[0] at this time).
```
batch = random_batch(12)
enc = EncoderRNN(input_lang.n_words, 256, 2, dropout=0.1).cuda()
enc = torch.nn.DataParallel(enc, device_ids=[0])
encoder_outputs, encoder_hidden = enc.forward(batch)  ## No errors
```

But when i try to parallel encoder, there is as error inside parallel_apply module:
```
enc = torch.nn.DataParallel(enc, device_ids=[0,1])
enc = torch.nn.DataParallel(enc, device_ids=[0,1])

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/d.parpulov/.virtualenvs/venv/local/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 22, in _worker
    var_input = var_input[0]
TypeError: 'int' object has no attribute '__getitem__'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/d.parpulov/.virtualenvs/venv/local/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 22, in _worker
    var_input = var_input[0]
TypeError: 'int' object has no attribute '__getitem__'

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-38-41625ee65e69> in <module>()
----> 1 encoder_outputs, encoder_hidden = enc.forward(batch)

/home/d.parpulov/.virtualenvs/venv/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.pyc in forward(self, *inputs, **kwargs)
     59             return self.module(*inputs[0], **kwargs[0])
     60         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
---> 61         outputs = self.parallel_apply(replicas, inputs, kwargs)
     62         return self.gather(outputs, self.output_device)
     63 

/home/d.parpulov/.virtualenvs/venv/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.pyc in parallel_apply(self, replicas, inputs, kwargs)
     69 
     70     def parallel_apply(self, replicas, inputs, kwargs):
---> 71         return parallel_apply(replicas, inputs, kwargs)
     72 
     73     def gather(self, outputs, output_device):

/home/d.parpulov/.virtualenvs/venv/local/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py in parallel_apply(modules, inputs, kwargs_tup)
     43     outputs = []
     44     for i in range(len(inputs)):
---> 45         output = results[i]
     46         if isinstance(output, Exception):
     47             raise output

KeyError: 0
```

unfortunately, I can't debug this error correctly.
Please, could you help me to parallelize batched seq2seq? Or maybe provide correct version of parallelizing? ;)
thank you!

**Comment by howardyclo** [comment]
Hi guys, I implemented more features based on this tutorial and added some notes.
Check out my repo here: https://github.com/howardyclo/pytorch-seq2seq-example/blob/master/seq2seq.ipynb

**Comment by physicsman** [comment]
I noticed some implementations of batch seq2seq with attention allow for an embedded size that is different then the hidden size. Is there a reason to match the two sizes?

**Comment by suwangcompling** [comment]
@spro Thanks for the nice code sample. I tried to run it out of the box, hit an error in this block:
`max_target_length = max(target_lengths)

# Prepare decoder input and outputs
decoder_input = Variable(torch.LongTensor([SOS_token] * small_batch_size))
decoder_hidden = encoder_hidden[:decoder_test.n_layers] # Use last (forward) hidden state from encoder
all_decoder_outputs = Variable(torch.zeros(max_target_length, small_batch_size, decoder_test.output_size))

if USE_CUDA:
    all_decoder_outputs = all_decoder_outputs.cuda()
    decoder_input = decoder_input.cuda()

# Run through decoder one time step at a time
for t in range(max_target_length):
    decoder_output, decoder_hidden, decoder_attn = decoder_test(
        decoder_input, decoder_hidden, encoder_outputs
    )
    all_decoder_outputs[t] = decoder_output # Store this step's outputs
    decoder_input = target_batches[t] # Next input is current target

# Test masked cross entropy loss
loss = masked_cross_entropy(
    all_decoder_outputs.transpose(0, 1).contiguous(),
    target_batches.transpose(0, 1).contiguous(),
    target_lengths
)
print('loss', loss.data[0])`
The error reads 
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-babf231e41ef> in <module>()
     13 for t in range(max_target_length):
     14     decoder_output, decoder_hidden, decoder_attn = decoder_test(
---> 15         decoder_input, decoder_hidden, encoder_outputs
     16     )
     17     all_decoder_outputs[t] = decoder_output # Store this step's outputs

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

<ipython-input-24-43d7954b3ba4> in forward(self, input_seq, last_hidden, encoder_outputs)
     35         # Calculate attention from current RNN state and all encoder outputs;
     36         # apply to encoder outputs to get weighted average
---> 37         attn_weights = self.attn(rnn_output, encoder_outputs)
     38         context = attn_weights.bmm(encoder_outputs.transpose(0, 1)) # B x S=1 x N
     39 

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

<ipython-input-22-61485b548d0f> in forward(self, hidden, encoder_outputs)
     27             # Calculate energy for each encoder output
     28             for i in range(max_len):
---> 29                 attn_energies[b, i] = self.score(hidden[:, b], encoder_outputs[i, b].unsqueeze(0))
     30 
     31         # Normalize energies to weights in range 0 to 1, resize to 1 x B x S

<ipython-input-22-61485b548d0f> in score(self, hidden, encoder_output)
     40         elif self.method == 'general':
     41             energy = self.attn(encoder_output)
---> 42             energy = hidden.dot(energy)
     43             return energy
     44 

RuntimeError: Expected argument self to have 1 dimension, but has 2`

**Comment by NLPScott** [comment]
@suwangcompling hidden = hidden.squeeze(), encoder_output = encoder_output.squeeze()
you can try it!
