### ISSUE TITLE
Error when I try to use the translation model on charchter level 

### ISSUE THREAD

**Issue by somah1411** [spro/practical-pytorch#71]
Traceback (most recent call last):
  File "/home/ealmanso/Data/python3 mhj/main.py", line 340, in <module>
    loss = train(input_variable, target_variable, encoder, decoder, encoder_optimizer, decoder_optimizer, criterion)
  File "/home/ealmanso/Data/python3 mhj/main.py", line 149, in train
    encoder_outputs, encoder_hidden = encoder(input_variable, encoder_hidden)
  File "/home/ealmanso/anaconda3/envs/my_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ealmanso/Data/python3 mhj/main.py", line 35, in forward
    embedded = self.embedding(word_inputs).view(seq_len, 1, -1)
  File "/home/ealmanso/anaconda3/envs/my_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ealmanso/anaconda3/envs/my_env/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 94, in forward
    self.scale_grad_by_freq, self.sparse
  File "/home/ealmanso/anaconda3/envs/my_env/lib/python3.6/site-packages/torch/nn/_functions/thnn/sparse.py", line 53, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, !torch.LongTensor!), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)

Process finished with exit code 1

**Comment by hunkim** [comment]
Try this one: https://github.com/hunkim/PyTorchZeroToAll/blob/master/12_5_char_rnn.py

I modified this code.
